kind: pipeline
type: docker
name: Test

platform:
  os: linux
  arch: arm64

steps:

- name: Fix drone limitation
  image: drone/git
  commands:
  - git fetch
  # - git fetch origin master
  - git fetch --tags
  - git fetch --all
  - chown -R 1000:1000 .

- name: Lint
  image: tedicreations/devtools:latest
  commands:
  - ./scripts/lint.sh

- name: Test
  image: tedicreations/devtools:latest
  commands:
  - git branch
  - git tag
  - ls -lsa
  - git status

- name: Build Posix
  image: tedicreations/devtools:latest
  commands:
  - make PORT_NAME=posix

- name: Build stm32f072rb
  image: tedicreations/devtools:latest
  commands:
  - make PORT_NAME=stm32f072rb

- name: Build tm4c123gh6pm
  image: tedicreations/devtools:latest
  commands:
  - make PORT_NAME=tm4c123gh6pm
