kind: pipeline
type: docker
name: Test

platform:
  os: linux
  arch: amd64

steps:

- name: Fix drone limitation
  image: drone/git
  commands:
  - |
      if [ "$(git symbolic-ref --short HEAD)" != "master" ]; then
        git fetch origin master:master
      fi
  - git fetch --tags
  - chown -R 1000:1000 .

- name: Analyse
  image: voidbuffer/devtools:latest
  commands:
  - ./scripts/shellcheck.sh
  - ./scripts/cppcheck.sh
  - ./scripts/pmccabe.sh

- name: Build posix
  image: voidbuffer/devtools:latest
  commands:
  - make PORT_NAME=posix

- name: Build stm32f072rb
  image: voidbuffer/devtools:latest
  commands:
  - make PORT_NAME=stm32f072rb

- name: Build tm4c123gh6pm
  image: voidbuffer/devtools:latest
  commands:
  - make PORT_NAME=tm4c123gh6pm

- name: Docs
  image: voidbuffer/devtools:latest
  commands:
  - ./scripts/doxygen.sh
