kind: pipeline
type: docker
name: Test

platform:
  os: linux
  arch: arm64

steps:

- name: Change permissions to user
  image: drone/git
  commands:
  - chown -R 1000:1000 .

- name: Lint
  image: tedicreations/devtools:latest
  commands:
  - ./script/lint.sh

- name: Build Posix
  image: tedicreations/devtools:latest
  commands:
  - make PORT_NAME=posix

- name: Build stm32f072rb
  image: tedicreations/devtools:latest
  commands:
  - make PORT_NAME=stm32f072rb

- name: Build tm4c123gh6pm
  image: tedicreations/devtools:latest
  commands:
  - make PORT_NAME=tm4c123gh6pm
