#!/usr/bin/env bash

# Calculate and display the memory consumption of a build

set -euo pipefail

usage()
{
	echo "Usage:"
	echo "get-fw-size <FILE> <MAX_FLASH_SIZE> <MAX_RAM_SIZE>"
}

main()
{
	if [  $# -le 2 ]
	then
		echo "This script requires 3 arguments."
		echo ""
		usage
		exit 1
	fi

	file="$1"
	max_flash="$2"
	max_ram="$3"

	readonly sizeTool="arm-none-eabi-size"

	# ---------------------------------------------------------------------

	function print_region() {
		size=$1
		max_size=$2
		name=$3

		if [[ ${max_size} == 0x* ]];
		then
			max_size="${max_size:2}"
			max_size=$(( 16#$max_size ))
		fi

		pct=$(( 100 * size / max_size ))
		echo "$name used: $size / $max_size ($pct%)"
	}

	raw=$("${sizeTool}" "${file}")

	# shellcheck disable=SC2086
	text=$(echo ${raw} | cut -d ' ' -f 7)
	# shellcheck disable=SC2086
	data=$(echo ${raw} | cut -d ' ' -f 8)
	# shellcheck disable=SC2086
	bss=$(echo ${raw} | cut -d ' ' -f 9)

	flash=$((text + data))
	ram=$((data + bss))

	print_region "${flash}" "${max_flash}" "Flash"
	print_region "${ram}"   "${max_ram}"   "RAM  "
}

main "$@"
